import React, { useEffect, useState, useRef } from 'react'
import ReactDOM from 'react-dom'
import api from '../api/client'
import { useTenant } from '../components/TenantContext'
import { useUser } from '../components/UserContext'
import { hasMinRole } from '../components/RequireRole'

type ScenarioType = 'best' | 'base' | 'worst' | 'custom' | 'ai_generated'
type AssumptionCategory = 'revenue' | 'expense' | 'asset' | 'liability' | 'depreciation' | 'tax' | 'other'

interface Assumption {
  assumption_category: AssumptionCategory
  assumption_key: string
  assumption_value: number
  assumption_unit: string
  notes: string
}

interface ScenarioItem {
  id: string
  scenario_name: string
  scenario_type: ScenarioType
  description?: string
  is_active: boolean
  created_at: string
  updated_at?: string
  created_by?: string
  assumptions?: Assumption[]
}

const TYPE_META: Record<ScenarioType, { label: string, color: string, icon: string, desc: string }> = {
  best:          { label: 'Best Case',      color: 'success', icon: 'arrow-up-circle-fill',  desc: 'Optimistic scenario — strong growth, controlled costs' },
  base:          { label: 'Base Case',      color: 'primary', icon: 'dash-circle-fill',        desc: 'Most-likely scenario based on current trends' },
  worst:         { label: 'Worst Case',     color: 'danger',  icon: 'arrow-down-circle-fill',  desc: 'Conservative scenario — weak revenue, higher costs' },
  custom:        { label: 'Custom',         color: 'info',    icon: 'sliders',                 desc: 'User-defined scenario' },
  ai_generated:  { label: 'AI Generated',   color: 'warning', icon: 'robot',                   desc: 'Scenario generated by AI model' },
}

const CAT_COLORS: Record<AssumptionCategory, string> = {
  revenue: 'success', expense: 'danger', asset: 'primary', liability: 'warning',
  depreciation: 'secondary', tax: 'dark', other: 'info',
}

function fmtDate(v: any) {
  if (!v) return '—'
  return new Date(v).toLocaleDateString('th-TH', { year: 'numeric', month: 'short', day: 'numeric' })
}

const BLANK_ASSUMPTION = (): Assumption => ({ assumption_category: 'revenue', assumption_key: '', assumption_value: 0, assumption_unit: '%', notes: '' })

export default function Scenarios() {
  const { tenantId } = useTenant()
  const { role } = useUser()
  const isAdmin = hasMinRole(role, 'admin')

  const [items, setItems] = useState<ScenarioItem[]>([])
  const [loading, setLoading] = useState(true)
  const [filterType, setFilterType] = useState<string>('all')
  const [filterStatus, setFilterStatus] = useState<string>('all')
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [detailCache, setDetailCache] = useState<Record<string, Assumption[]>>({})

  // Create modal state
  const [showModal, setShowModal] = useState(false)
  const [form, setForm] = useState({
    scenario_name: '',
    scenario_type: 'base' as ScenarioType,
    description: '',
    is_active: true,
  })
  const [assumptions, setAssumptions] = useState<Assumption[]>([])
  const [creating, setCreating] = useState(false)

  // Edit modal state
  const [editTarget, setEditTarget] = useState<ScenarioItem | null>(null)
  const [editDesc, setEditDesc] = useState('')
  const [editActive, setEditActive] = useState(true)
  const [saving, setSaving] = useState(false)

  // Toast
  const [toast, setToast] = useState<{ msg: string; type: 'success' | 'danger' } | null>(null)
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  function showToast(msg: string, type: 'success' | 'danger' = 'success') {
    setToast({ msg, type })
    if (toastTimer.current) clearTimeout(toastTimer.current)
    toastTimer.current = setTimeout(() => setToast(null), 3500)
  }

  async function load() {
    if (!tenantId) { setItems([]); setLoading(false); return }
    setLoading(true)
    try {
      const r = await api.get('/scenarios')
      setItems(r.data || [])
    } catch (e) { console.error(e) }
    setLoading(false)
  }

  useEffect(() => { load() }, [tenantId])

  async function loadDetail(id: string) {
    if (detailCache[id]) return
    try {
      const r = await api.get(`/scenarios/${id}`)
      setDetailCache(prev => ({ ...prev, [id]: r.data?.assumptions || [] }))
    } catch {}
  }

  function toggleExpand(id: string) {
    if (expandedId === id) { setExpandedId(null); return }
    setExpandedId(id)
    loadDetail(id)
  }

  // ── Active Toggle ──
  async function toggleActive(item: ScenarioItem) {
    try {
      await api.put(`/scenarios/${item.id}`, { is_active: !item.is_active })
      setItems(prev => prev.map(s => s.id === item.id ? { ...s, is_active: !s.is_active } : s))
      showToast(`${item.scenario_name} ${item.is_active ? 'deactivated' : 'activated'}`)
    } catch (e: any) {
      showToast(e?.response?.data?.message || 'Failed to update', 'danger')
    }
  }

  // ── Delete ──
  async function deleteScenario(item: ScenarioItem) {
    if (!confirm(`Delete scenario "${item.scenario_name}"?\nThis will also delete all assumptions.`)) return
    try {
      await api.delete(`/scenarios/${item.id}`)
      setItems(prev => prev.filter(s => s.id !== item.id))
      showToast(`Scenario "${item.scenario_name}" deleted`)
    } catch (e: any) {
      showToast(e?.response?.data?.message || 'Failed to delete', 'danger')
    }
  }

  // ── Create Defaults ──
  async function createDefaults() {
    if (!confirm('Create default Best/Base/Worst Case scenarios?')) return
    try {
      await api.post('/scenarios/defaults')
      showToast('Default scenarios created!')
      load()
    } catch (e: any) {
      showToast(e?.response?.data?.message || 'Failed', 'danger')
    }
  }

  // ── Create Scenario ──
  async function handleCreate(e: React.FormEvent) {
    e.preventDefault()
    if (!form.scenario_name.trim()) return
    setCreating(true)
    try {
      const payload = {
        scenario_name: form.scenario_name.trim(),
        scenario_type: form.scenario_type,
        description: form.description.trim() || null,
        is_active: form.is_active,
        assumptions: assumptions.filter(a => a.assumption_key.trim()),
      }
      const r = await api.post('/scenarios', payload)
      const created = r.data?.scenario || r.data
      setItems(prev => [created, ...prev])
      setForm({ scenario_name: '', scenario_type: 'base', description: '', is_active: true })
      setAssumptions([])
      setShowModal(false)
      showToast(`Scenario "${created.scenario_name}" created!`)
    } catch (err: any) {
      showToast(err?.response?.data?.message || err?.message || 'Failed to create', 'danger')
    } finally { setCreating(false) }
  }

  // ── Edit Scenario ──
  function openEdit(item: ScenarioItem) {
    setEditTarget(item)
    setEditDesc(item.description || '')
    setEditActive(item.is_active)
  }

  async function handleEdit(e: React.FormEvent) {
    e.preventDefault()
    if (!editTarget) return
    setSaving(true)
    try {
      await api.put(`/scenarios/${editTarget.id}`, { description: editDesc, is_active: editActive })
      setItems(prev => prev.map(s => s.id === editTarget.id ? { ...s, description: editDesc, is_active: editActive } : s))
      setEditTarget(null)
      showToast('Scenario updated!')
    } catch (e: any) {
      showToast(e?.response?.data?.message || 'Failed to update', 'danger')
    } finally { setSaving(false) }
  }

  // ── Filtering ──
  const filtered = items.filter(s => {
    const typeOk = filterType === 'all' || s.scenario_type === filterType
    const statusOk = filterStatus === 'all' || (filterStatus === 'active' ? s.is_active : !s.is_active)
    return typeOk && statusOk
  })

  // ── KPI counts ──
  const activeCount = items.filter(s => s.is_active).length
  const inactiveCount = items.length - activeCount
  const typeCounts = items.reduce((acc, s) => { acc[s.scenario_type] = (acc[s.scenario_type] || 0) + 1; return acc }, {} as Record<string, number>)

  return (
    <>
      {/* ── Toast ── */}
      {toast && (
        <div className={`toast show position-fixed text-bg-${toast.type}`} style={{ top: 16, right: 16, zIndex: 9999, minWidth: 280 }}>
          <div className="toast-body d-flex align-items-center gap-2">
            <i className={`bi bi-${toast.type === 'success' ? 'check-circle-fill' : 'exclamation-triangle-fill'}`}></i>
            {toast.msg}
            <button className="btn-close btn-close-white ms-auto" onClick={() => setToast(null)}></button>
          </div>
        </div>
      )}

      {/* ── Page Header ── */}
      <div className="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
        <div>
          <h4 className="mb-0 fw-bold"><i className="bi bi-diagram-3 me-2 text-primary"></i>Financial Scenarios</h4>
          <small className="text-muted">Manage budget, forecast and planning scenarios for CFO analysis</small>
        </div>
        <div className="d-flex gap-2 flex-wrap">
          <button className="btn btn-outline-secondary btn-sm" onClick={load}>
            <i className="bi bi-arrow-clockwise me-1"></i>Refresh
          </button>
          {isAdmin && (
            <button className="btn btn-outline-info btn-sm" onClick={createDefaults}>
              <i className="bi bi-magic me-1"></i>Create Defaults
            </button>
          )}
          <button className="btn btn-primary btn-sm" onClick={() => setShowModal(true)}>
            <i className="bi bi-plus-circle me-1"></i>New Scenario
          </button>
        </div>
      </div>

      {/* ── KPI Strip ── */}
      <div className="row g-3 mb-3">
        <div className="col-6 col-md-3">
          <div className="info-box mb-0">
            <span className="info-box-icon text-bg-primary shadow-sm"><i className="bi bi-diagram-3-fill"></i></span>
            <div className="info-box-content">
              <span className="info-box-text">Total Scenarios</span>
              <span className="info-box-number">{items.length}</span>
              <div className="progress mt-1"><div className="progress-bar bg-primary" style={{ width: '100%' }}></div></div>
              <span className="progress-description">All planning scenarios</span>
            </div>
          </div>
        </div>
        <div className="col-6 col-md-3">
          <div className="info-box mb-0">
            <span className="info-box-icon text-bg-success shadow-sm"><i className="bi bi-check-circle-fill"></i></span>
            <div className="info-box-content">
              <span className="info-box-text">Active</span>
              <span className="info-box-number text-success">{activeCount}</span>
              <div className="progress mt-1"><div className="progress-bar bg-success" style={{ width: `${items.length ? activeCount / items.length * 100 : 0}%` }}></div></div>
              <span className="progress-description">In use</span>
            </div>
          </div>
        </div>
        <div className="col-6 col-md-3">
          <div className="info-box mb-0">
            <span className="info-box-icon text-bg-secondary shadow-sm"><i className="bi bi-pause-circle-fill"></i></span>
            <div className="info-box-content">
              <span className="info-box-text">Inactive</span>
              <span className="info-box-number text-secondary">{inactiveCount}</span>
              <div className="progress mt-1"><div className="progress-bar bg-secondary" style={{ width: `${items.length ? inactiveCount / items.length * 100 : 0}%` }}></div></div>
              <span className="progress-description">Archived / disabled</span>
            </div>
          </div>
        </div>
        <div className="col-6 col-md-3">
          <div className="info-box mb-0">
            <span className="info-box-icon text-bg-info shadow-sm"><i className="bi bi-bar-chart-steps"></i></span>
            <div className="info-box-content">
              <span className="info-box-text">Scenario Types</span>
              <span className="info-box-number">{Object.keys(typeCounts).length}</span>
              <div className="progress mt-1"><div className="progress-bar bg-info" style={{ width: '100%' }}></div></div>
              <span className="progress-description">{Object.entries(typeCounts).map(([t,c]) => `${c} ${t}`).join(' · ') || 'No types yet'}</span>
            </div>
          </div>
        </div>
      </div>

      {/* ── CFO Scenario Types Guide ── */}
      <div className="card mb-3 border-0 bg-light">
        <div className="card-body py-2">
          <div className="row g-2 align-items-center">
            <div className="col-auto text-muted small fw-semibold">Scenario Types:</div>
            {(Object.entries(TYPE_META) as [ScenarioType, typeof TYPE_META[ScenarioType]][]).map(([k, m]) => (
              <div key={k} className="col-auto">
                <span className={`badge text-bg-${m.color} me-1`}><i className={`bi bi-${m.icon} me-1`}></i>{m.label}</span>
                <small className="text-muted d-none d-md-inline">{m.desc}</small>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Filter Bar ── */}
      <div className="card mb-3">
        <div className="card-body py-2">
          <div className="d-flex gap-3 flex-wrap align-items-center">
            <div>
              <small className="text-muted me-2 fw-semibold">Type:</small>
              {['all', 'best', 'base', 'worst', 'custom', 'ai_generated'].map(t => (
                <button key={t} onClick={() => setFilterType(t)}
                  className={`btn btn-sm me-1 ${filterType === t ? `btn-primary` : 'btn-outline-secondary'}`}
                  style={{ textTransform: 'capitalize' }}>
                  {t === 'all' ? 'All' : TYPE_META[t as ScenarioType]?.label || t}
                  {t !== 'all' && typeCounts[t] !== undefined ? ` (${typeCounts[t]})` : ''}
                </button>
              ))}
            </div>
            <div className="ms-auto">
              <small className="text-muted me-2 fw-semibold">Status:</small>
              {[['all','All'], ['active','Active'], ['inactive','Inactive']].map(([v, l]) => (
                <button key={v} onClick={() => setFilterStatus(v)}
                  className={`btn btn-sm me-1 ${filterStatus === v ? 'btn-primary' : 'btn-outline-secondary'}`}>
                  {l}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* ── Scenarios Grid ── */}
      {loading ? (
        <div className="card"><div className="card-body text-center py-5">
          <div className="spinner-border text-primary" role="status"></div>
          <p className="mt-3 text-muted">Loading scenarios...</p>
        </div></div>
      ) : filtered.length === 0 ? (
        <div className="card">
          <div className="card-body text-center py-5">
            <i className="bi bi-diagram-3 text-muted" style={{ fontSize: 56 }}></i>
            <h5 className="mt-3">No Scenarios Found</h5>
            <p className="text-muted">
              {items.length === 0
                ? 'Create your first scenario to start organizing financial projections.'
                : 'No scenarios match the current filter. Try changing the filters above.'}
            </p>
            <div className="d-flex justify-content-center gap-2 mt-3">
              <button className="btn btn-primary" onClick={() => setShowModal(true)}>
                <i className="bi bi-plus-circle me-1"></i>New Scenario
              </button>
              {isAdmin && items.length === 0 && (
                <button className="btn btn-outline-info" onClick={createDefaults}>
                  <i className="bi bi-magic me-1"></i>Create Defaults (Best/Base/Worst)
                </button>
              )}
            </div>
          </div>
        </div>
      ) : (
        <div className="row g-3">
          {filtered.map(item => {
            const meta = TYPE_META[item.scenario_type] || TYPE_META.custom
            const expanded = expandedId === item.id
            const assumptions = detailCache[item.id] || []
            return (
              <div key={item.id} className="col-md-6 col-xl-4">
                <div className={`card h-100 border-${meta.color} border-start border-4`} style={{ borderLeftWidth: 5 }}>
                  <div className="card-header d-flex align-items-start gap-2 pb-2">
                    <div className="flex-grow-1 min-w-0">
                      <div className="d-flex align-items-center gap-2 flex-wrap">
                        <span className={`badge text-bg-${meta.color}`}>
                          <i className={`bi bi-${meta.icon} me-1`}></i>{meta.label}
                        </span>
                        <span className={`badge ${item.is_active ? 'text-bg-success' : 'text-bg-secondary'}`}>
                          <i className={`bi bi-${item.is_active ? 'check-circle' : 'pause-circle'} me-1`}></i>
                          {item.is_active ? 'Active' : 'Inactive'}
                        </span>
                      </div>
                      <h6 className="mt-2 mb-0 fw-bold">{item.scenario_name}</h6>
                      {item.description && <small className="text-muted">{item.description}</small>}
                    </div>
                    <div className="dropdown">
                      <button className="btn btn-sm btn-outline-secondary" data-bs-toggle="dropdown">
                        <i className="bi bi-three-dots-vertical"></i>
                      </button>
                      <ul className="dropdown-menu dropdown-menu-end">
                        <li>
                          <button className="dropdown-item" onClick={() => openEdit(item)}>
                            <i className="bi bi-pencil me-2"></i>Edit
                          </button>
                        </li>
                        <li>
                          <button className="dropdown-item" onClick={() => toggleActive(item)}>
                            <i className={`bi bi-${item.is_active ? 'pause-circle' : 'play-circle'} me-2`}></i>
                            {item.is_active ? 'Deactivate' : 'Activate'}
                          </button>
                        </li>
                        {isAdmin && <li><hr className="dropdown-divider" /></li>}
                        {isAdmin && (
                          <li>
                            <button className="dropdown-item text-danger" onClick={() => deleteScenario(item)}>
                              <i className="bi bi-trash me-2"></i>Delete
                            </button>
                          </li>
                        )}
                      </ul>
                    </div>
                  </div>

                  <div className="card-body py-2">
                    <div className="row g-2 text-center">
                      <div className="col-6">
                        <small className="text-muted d-block">Created By</small>
                        <span className="fw-semibold small">{item.created_by || '—'}</span>
                      </div>
                      <div className="col-6">
                        <small className="text-muted d-block">Created</small>
                        <span className="fw-semibold small">{fmtDate(item.created_at)}</span>
                      </div>
                    </div>
                    {item.updated_at && item.updated_at !== item.created_at && (
                      <div className="text-center mt-1">
                        <small className="text-muted">Updated {fmtDate(item.updated_at)}</small>
                      </div>
                    )}
                  </div>

                  <div className="card-footer pt-0 border-0 bg-transparent">
                    <button
                      className="btn btn-sm w-100 btn-outline-secondary"
                      onClick={() => toggleExpand(item.id)}
                    >
                      <i className={`bi bi-chevron-${expanded ? 'up' : 'down'} me-1`}></i>
                      {expanded ? 'Hide Assumptions' : 'Show Assumptions'}
                      {detailCache[item.id] !== undefined && (
                        <span className={`badge ms-2 text-bg-${detailCache[item.id].length > 0 ? 'info' : 'secondary'}`}>
                          {detailCache[item.id].length}
                        </span>
                      )}
                    </button>

                    {expanded && (
                      <div className="mt-2">
                        {assumptions.length === 0 ? (
                          <div className="text-center py-3 text-muted small">
                            <i className="bi bi-table d-block mb-1"></i>
                            No assumptions set. Add assumptions when creating a new scenario.
                          </div>
                        ) : (
                          <div className="table-responsive">
                            <table className="table table-sm table-hover mb-0">
                              <thead className="table-light">
                                <tr>
                                  <th>Category</th>
                                  <th>Key</th>
                                  <th className="text-end">Value</th>
                                  <th>Unit</th>
                                  <th>Notes</th>
                                </tr>
                              </thead>
                              <tbody>
                                {assumptions.map((a, i) => (
                                  <tr key={i}>
                                    <td>
                                      <span className={`badge text-bg-${CAT_COLORS[a.assumption_category as AssumptionCategory] || 'secondary'} text-capitalize`}>
                                        {a.assumption_category}
                                      </span>
                                    </td>
                                    <td className="fw-semibold small">{a.assumption_key}</td>
                                    <td className="text-end">{a.assumption_value}</td>
                                    <td className="text-muted small">{a.assumption_unit}</td>
                                    <td className="text-muted small">{a.notes || '—'}</td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* ── Scenario Summary Table (below grid, compact) ── */}
      {items.length > 0 && (
        <div className="card mt-3">
          <div className="card-header">
            <h3 className="card-title"><i className="bi bi-table me-2"></i>Scenario Summary</h3>
          </div>
          <div className="card-body p-0">
            <div className="table-responsive">
              <table className="table table-hover mb-0">
                <thead className="table-light">
                  <tr>
                    <th>#</th>
                    <th>Scenario</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Created By</th>
                    <th>Created</th>
                    <th>Last Updated</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((item, idx) => {
                    const meta = TYPE_META[item.scenario_type] || TYPE_META.custom
                    return (
                      <tr key={item.id}>
                        <td className="text-muted small">{idx + 1}</td>
                        <td>
                          <div className="fw-semibold">{item.scenario_name}</div>
                          {item.description && <small className="text-muted">{item.description}</small>}
                        </td>
                        <td><span className={`badge text-bg-${meta.color}`}>{meta.label}</span></td>
                        <td>
                          <div className="form-check form-switch mb-0" title={item.is_active ? 'Click to deactivate' : 'Click to activate'}>
                            <input className="form-check-input" type="checkbox" role="switch"
                              checked={item.is_active} onChange={() => toggleActive(item)} />
                            <label className={`form-check-label small ${item.is_active ? 'text-success' : 'text-muted'}`}>
                              {item.is_active ? 'Active' : 'Inactive'}
                            </label>
                          </div>
                        </td>
                        <td className="small">{item.created_by || '—'}</td>
                        <td className="small">{fmtDate(item.created_at)}</td>
                        <td className="small">{fmtDate(item.updated_at)}</td>
                        <td>
                          <div className="d-flex gap-1">
                            <button className="btn btn-xs btn-outline-primary btn-sm py-0 px-2" onClick={() => openEdit(item)} title="Edit">
                              <i className="bi bi-pencil"></i>
                            </button>
                            {isAdmin && (
                              <button className="btn btn-xs btn-outline-danger btn-sm py-0 px-2" onClick={() => deleteScenario(item)} title="Delete">
                                <i className="bi bi-trash"></i>
                              </button>
                            )}
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
          <div className="card-footer">
            <small className="text-muted">
              {filtered.length} of {items.length} scenarios shown · {activeCount} active
            </small>
          </div>
        </div>
      )}

      {/* ── Create Scenario Modal ── */}
      {showModal && ReactDOM.createPortal(
        <div style={{ background: 'rgba(0,0,0,0.55)', zIndex: 9999, position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }} onClick={e => { if (e.target === e.currentTarget) setShowModal(false) }}>
          <div style={{ width: '100%', maxWidth: 780, maxHeight: '92vh', display: 'flex', flexDirection: 'column', borderRadius: 12, overflow: 'hidden', boxShadow: '0 20px 60px rgba(0,0,0,0.35)', background: '#fff' }}>
            <form style={{ display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' }} onSubmit={handleCreate}>
              <div style={{ background: 'linear-gradient(135deg,#1a6fc7,#0d47a1)', padding: '1rem 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0 }}>
                <div className="d-flex align-items-center gap-2">
                  <div style={{ background: 'rgba(255,255,255,0.2)', borderRadius: 8, width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>
                    <i className="bi bi-plus-circle text-white"></i>
                  </div>
                  <div>
                    <div className="fw-bold text-white" style={{ fontSize: '1rem', lineHeight: 1.2 }}>Create New Scenario</div>
                    <div style={{ color: 'rgba(255,255,255,0.75)', fontSize: '0.78rem' }}>Define assumptions and projections for this scenario</div>
                  </div>
                </div>
                <button type="button" className="btn-close btn-close-white" onClick={() => setShowModal(false)}></button>
              </div>
              <div className="modal-body" style={{ overflowY: 'auto', flex: 1, padding: '1.5rem' }}>

                {/* Basic Info */}
                <div className="row g-3 mb-3">
                  <div className="col-md-8">
                    <label className="form-label fw-semibold">Scenario Name <span className="text-danger">*</span></label>
                    <input type="text" className="form-control" placeholder="e.g. Budget 2026, Q2 Forecast, Conservative Plan"
                      value={form.scenario_name} onChange={e => setForm(f => ({ ...f, scenario_name: e.target.value }))} required />
                  </div>
                  <div className="col-md-4">
                    <label className="form-label fw-semibold">Type <span className="text-danger">*</span></label>
                    <select className="form-select" value={form.scenario_type} onChange={e => setForm(f => ({ ...f, scenario_type: e.target.value as ScenarioType }))}>
                      <option value="best">Best Case — Optimistic</option>
                      <option value="base">Base Case — Most Likely</option>
                      <option value="worst">Worst Case — Conservative</option>
                      <option value="custom">Custom</option>
                      <option value="ai_generated">AI Generated</option>
                    </select>
                  </div>
                </div>

                <div className="mb-3">
                  <label className="form-label fw-semibold">Description</label>
                  <textarea className="form-control" rows={2} placeholder="Optional: describe the assumptions and context for this scenario"
                    value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} />
                </div>

                <div className="mb-3">
                  <div className="form-check form-switch">
                    <input className="form-check-input" type="checkbox" role="switch" id="isActiveSwitch"
                      checked={form.is_active} onChange={e => setForm(f => ({ ...f, is_active: e.target.checked }))} />
                    <label className="form-check-label fw-semibold" htmlFor="isActiveSwitch">
                      Active (scenario will be available for use in financial statements)
                    </label>
                  </div>
                </div>

                {/* Type Preview */}
                {form.scenario_type && (
                  <div className={`alert alert-${TYPE_META[form.scenario_type]?.color || 'secondary'} py-2`}>
                    <i className={`bi bi-${TYPE_META[form.scenario_type]?.icon} me-2`}></i>
                    <strong>{TYPE_META[form.scenario_type]?.label}:</strong> {TYPE_META[form.scenario_type]?.desc}
                  </div>
                )}

                {/* Assumptions Section */}
                <hr />
                <div className="d-flex justify-content-between align-items-center mb-2">
                  <h6 className="mb-0 fw-bold"><i className="bi bi-sliders me-2"></i>Assumptions <span className="text-muted fw-normal">(Optional)</span></h6>
                  <button type="button" className="btn btn-outline-primary btn-sm" onClick={() => setAssumptions(prev => [...prev, BLANK_ASSUMPTION()])}>
                    <i className="bi bi-plus me-1"></i>Add Row
                  </button>
                </div>
                <p className="text-muted small mb-2">Define growth rates, cost changes, and other financial assumptions driving this scenario.</p>

                {assumptions.length === 0 ? (
                  <div className="text-center py-3 bg-light rounded text-muted small">
                    No assumptions yet. Click "Add Row" to define scenario assumptions.
                  </div>
                ) : (
                  <div className="table-responsive">
                    <table className="table table-sm table-bordered align-middle mb-0">
                      <thead className="table-light">
                        <tr>
                          <th style={{ minWidth: 130 }}>Category</th>
                          <th style={{ minWidth: 130 }}>Key / Metric</th>
                          <th style={{ minWidth: 90 }}>Value</th>
                          <th style={{ minWidth: 70 }}>Unit</th>
                          <th>Notes</th>
                          <th style={{ width: 40 }}></th>
                        </tr>
                      </thead>
                      <tbody>
                        {assumptions.map((a, i) => (
                          <tr key={i}>
                            <td>
                              <select className="form-select form-select-sm" value={a.assumption_category}
                                onChange={e => setAssumptions(prev => prev.map((x, j) => j === i ? { ...x, assumption_category: e.target.value as AssumptionCategory } : x))}>
                                {(['revenue','expense','asset','liability','depreciation','tax','other'] as AssumptionCategory[]).map(c => (
                                  <option key={c} value={c}>{c.charAt(0).toUpperCase() + c.slice(1)}</option>
                                ))}
                              </select>
                            </td>
                            <td>
                              <input className="form-control form-control-sm" placeholder="e.g. growth_rate" value={a.assumption_key}
                                onChange={e => setAssumptions(prev => prev.map((x, j) => j === i ? { ...x, assumption_key: e.target.value } : x))} />
                            </td>
                            <td>
                              <input type="number" step="any" className="form-control form-control-sm" value={a.assumption_value}
                                onChange={e => setAssumptions(prev => prev.map((x, j) => j === i ? { ...x, assumption_value: Number(e.target.value) } : x))} />
                            </td>
                            <td>
                              <input className="form-control form-control-sm" placeholder="%" value={a.assumption_unit}
                                onChange={e => setAssumptions(prev => prev.map((x, j) => j === i ? { ...x, assumption_unit: e.target.value } : x))} />
                            </td>
                            <td>
                              <input className="form-control form-control-sm" placeholder="Optional" value={a.notes}
                                onChange={e => setAssumptions(prev => prev.map((x, j) => j === i ? { ...x, notes: e.target.value } : x))} />
                            </td>
                            <td className="text-center">
                              <button type="button" className="btn btn-sm btn-outline-danger py-0 px-1"
                                onClick={() => setAssumptions(prev => prev.filter((_, j) => j !== i))}>
                                <i className="bi bi-x"></i>
                              </button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {/* Quick Templates */}
                <div className="mt-2">
                  <small className="text-muted fw-semibold">Quick templates: </small>
                  {[
                    { label: 'Revenue Growth', assumption_category: 'revenue' as AssumptionCategory, assumption_key: 'revenue_growth', assumption_value: 10, assumption_unit: '%', notes: '' },
                    { label: 'Cost Reduction', assumption_category: 'expense' as AssumptionCategory, assumption_key: 'cost_reduction', assumption_value: 5, assumption_unit: '%', notes: '' },
                    { label: 'Tax Rate', assumption_category: 'tax' as AssumptionCategory, assumption_key: 'corporate_tax_rate', assumption_value: 20, assumption_unit: '%', notes: '' },
                    { label: 'Depreciation', assumption_category: 'depreciation' as AssumptionCategory, assumption_key: 'depreciation_rate', assumption_value: 10, assumption_unit: '%/yr', notes: '' },
                  ].map(t => (
                    <button key={t.label} type="button" className="btn btn-xs btn-outline-secondary btn-sm me-1 mb-1"
                      onClick={() => setAssumptions(prev => [...prev, { assumption_category: t.assumption_category, assumption_key: t.assumption_key, assumption_value: t.assumption_value, assumption_unit: t.assumption_unit, notes: t.notes }])}>
                      + {t.label}
                    </button>
                  ))}
                </div>
              </div>
              <div className="modal-footer" style={{ borderTop: '1px solid #e9ecef', background: '#f8f9fa', padding: '0.875rem 1.5rem' }}>
                <button type="button" className="btn btn-outline-secondary" onClick={() => setShowModal(false)}><i className="bi bi-x-lg me-1"></i>Cancel</button>
                <button type="submit" className="btn btn-primary px-4" disabled={creating || !form.scenario_name.trim()}>
                  {creating ? <><span className="spinner-border spinner-border-sm me-1"></span>Creating...</> : <><i className="bi bi-check-circle me-1"></i>Create Scenario</>}
                </button>
              </div>
            </form>
          </div>
        </div>
      , document.body)}

      {/* ── Edit Scenario Modal ── */}
      {editTarget && ReactDOM.createPortal(
        <div style={{ background: 'rgba(0,0,0,0.55)', zIndex: 9999, position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1rem' }} onClick={e => { if (e.target === e.currentTarget) setEditTarget(null) }}>
          <div style={{ width: '100%', maxWidth: 520, borderRadius: 12, overflow: 'hidden', boxShadow: '0 20px 60px rgba(0,0,0,0.35)', background: '#fff' }}>
            <form onSubmit={handleEdit}>
              <div style={{ background: 'linear-gradient(135deg,#1a6fc7,#0d47a1)', padding: '1rem 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div className="d-flex align-items-center gap-2">
                  <div style={{ background: 'rgba(255,255,255,0.2)', borderRadius: 8, width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 18 }}>
                    <i className="bi bi-pencil text-white"></i>
                  </div>
                  <div>
                    <div className="fw-bold text-white" style={{ fontSize: '1rem', lineHeight: 1.2 }}>Edit Scenario</div>
                    <div style={{ color: 'rgba(255,255,255,0.75)', fontSize: '0.78rem' }}>{editTarget.scenario_name}</div>
                  </div>
                </div>
                <button type="button" className="btn-close btn-close-white" onClick={() => setEditTarget(null)}></button>
              </div>
              <div className="modal-body">
                <div className="mb-3">
                  <label className="form-label fw-semibold">Scenario Name</label>
                  <input className="form-control" value={editTarget.scenario_name} disabled />
                  <div className="form-text text-muted">Name cannot be changed after creation.</div>
                </div>
                <div className="mb-3">
                  <label className="form-label fw-semibold">Type</label>
                  <input className="form-control" value={TYPE_META[editTarget.scenario_type]?.label || editTarget.scenario_type} disabled />
                </div>
                <div className="mb-3">
                  <label className="form-label fw-semibold">Description</label>
                  <textarea className="form-control" rows={3} value={editDesc} onChange={e => setEditDesc(e.target.value)}
                    placeholder="Describe this scenario..." />
                </div>
                <div className="form-check form-switch">
                  <input className="form-check-input" type="checkbox" role="switch" id="editActiveSwitch"
                    checked={editActive} onChange={e => setEditActive(e.target.checked)} />
                  <label className="form-check-label fw-semibold" htmlFor="editActiveSwitch">
                    Active (available for financial statements)
                  </label>
                </div>
              </div>
              <div className="modal-footer" style={{ borderTop: '1px solid #e9ecef', background: '#f8f9fa', padding: '0.875rem 1.5rem' }}>
                <button type="button" className="btn btn-outline-secondary" onClick={() => setEditTarget(null)}><i className="bi bi-x-lg me-1"></i>Cancel</button>
                <button type="submit" className="btn btn-primary px-4" disabled={saving}>
                  {saving ? <><span className="spinner-border spinner-border-sm me-1"></span>Saving...</> : <><i className="bi bi-check-circle me-1"></i>Save Changes</>}
                </button>
              </div>
            </form>
          </div>
        </div>
      , document.body)}
    </>
  )
}

